logbook:
  predicate:
    exclude[0]:
      path: /actuator/**
logging:
  file:
    name: ${spring.application.home:.}/logs/${spring.application.name}.log
  level:
    com.netflix.discovery: false
management:
  endpoint:
    configprops:
      show-values: ALWAYS
    env:
      show-values: ALWAYS
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
      profiles: ${spring.profiles.active}
  observations:
    key-values:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        step: 10s
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${TRACER_HOST:http://localhost:9411}/api/v2/spans
server:
  port: 9800
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  application:
    name: spring-admin
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      indent_output: true
  mvc:
    problemdetails:
      enabled: true
  output:
    ansi:
      enabled: always
  profiles:
    default: local
spring.cloud.discovery.client:
  composite-indicator:
    enabled: false
