{
 "title": "PostgreSQL Exporter",
 "description": "postgres exporter Dashboard for display important postgreSQL metric",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values({job=\"postgres-exporter\"}, instance)"
   },
   { "name": "Database", "query": "label_values(datname)" },
   { "name": "Interval", "query": "30sec,1m,10m,30m,1h,6h,12h,1d" },
   { "name": "query0", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  {
   "title": "Global Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_server_version_num", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Max Replication Lag",
   "type": "stat",
   "description": "Max Replication lag behind master in seconds\n\nOnly available on a standby system.\n\nSource: pg_last_xact_replay_timestamp\n\nUse: pg_stat_replication for Details.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "pg_replication_lag_seconds", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Active clients",
   "type": "stat",
   "description": "Clients executing Statements.\n\nSource: pg_stat_activity",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node) (pg_stat_activity_count{state=\"active\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(node) (pg_stat_database_blks_hit) * 100) / (sum by(node) (pg_stat_database_blks_hit) + sum by(node) (pg_stat_database_blks_read))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connections used",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(node) (pg_stat_database_numbackends) / max by(node) (pg_settings_max_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node) (pg_stat_database_xact_commit) / (sum by(node) (pg_stat_database_xact_commit) + sum by(node) (pg_stat_database_xact_rollback))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Uptime",
   "type": "stat",
   "description": "Source: pg_postmaster_start_time()",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max by(node) (process_start_time_seconds{job=\"pg-0\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max by(node) (process_start_time_seconds{job=\"pg-1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node) (rate(pg_stat_database_xact_commit[$Interval])) + sum by(node) (rate(pg_stat_database_xact_rollback[$Interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "stat",
   "description": "Statements executed per Minute.\n\nSource: pg_stat_statements.calls",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Total database size",
   "type": "stat",
   "description": "Size of all databases in $Instance.\n\nSource: pg_database_size()",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node) (pg_database_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average query runtime",
   "type": "stat",
   "description": "Source: pg_stat_statements.total_time / pg_stat_statements.calls",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((delta(pg_stat_statements_total_time_seconds{instance=\"$Instance\"}[$Interval])))/sum((delta(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "description": "Setting: shared_buffers in PostgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "Setting: max_connections in postgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node) (pg_settings_max_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections by state (stacked)",
   "type": "timeseries",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state, node) (pg_stat_activity_count)",
     "legendFormat": "{{node}}: {{state}}"
    }
   ]
  },
  {
   "title": "Connections by database (stacked)",
   "type": "timeseries",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(datname, node) (pg_stat_activity_count)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(pg_stat_database_xact_commit[$Interval]))",
     "legendFormat": "{{node}}: committed"
    },
    {
     "expr": "sum by(node) (rate(pg_stat_database_xact_rollback[$Interval]))",
     "legendFormat": "{{node}}: rollback"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "timeseries",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(pg_stat_database_tup_inserted[$Interval]))",
     "legendFormat": "{{node}}: Inserts"
    },
    {
     "expr": "sum by(node) (rate(pg_stat_database_tup_updated[$Interval]))",
     "legendFormat": "{{node}}: Updates"
    },
    {
     "expr": "sum by(node) (rate(pg_stat_database_tup_deleted[$Interval]))",
     "legendFormat": "{{node}}: Deletes"
    }
   ]
  },
  {
   "title": "I/O Read/Write time",
   "type": "timeseries",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(pg_stat_database_blk_read_time[$Interval]))",
     "legendFormat": "{{node}}: blk_read_time"
    },
    {
     "expr": "sum by(node) (rate(pg_stat_database_blk_write_time[$Interval]))",
     "legendFormat": "{{node}}: blk_read_time"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "timeseries",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(pg_stat_database_tup_fetched[$Interval]))",
     "legendFormat": "{{node}}: Fetched"
    },
    {
     "expr": "sum by(node) (rate(pg_stat_database_tup_returned[$Interval]))",
     "legendFormat": "{{node}}: Returned"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "timeseries",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(mode, node) (pg_locks_count)",
     "legendFormat": "{{node}}: {{mode}}"
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "timeseries",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(datname, node) (rate(pg_stat_database_deadlocks[$Interval]))",
     "legendFormat": "{{node}}: {{datname}}"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "timeseries",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(datname, node) (rate(pg_stat_database_temp_files[$Interval]))",
     "legendFormat": "{{node}}: {{datname}}"
    }
   ]
  },
  {
   "title": "Replication lag ",
   "type": "timeseries",
   "description": "Lag behind master in seconds.\n\nOnly available on a standby System.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(node) (pg_replication_lag_seconds)",
     "legendFormat": "{{node}}: lag "
    }
   ]
  }
 ]
}